// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RemovePunctuation
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("cleaned")]
        public string Cleaned { get; set; }

        [JsonProperty("removed")]
        public string[] Removed { get; set; }

        [JsonProperty("removed_count")]
        public long RemovedCount { get; set; }
    }
}
